# serverless.yml
org: tihechen
app: free-mint-api
service: free-mint-api
frameworkVersion: "3"
useDotenv: true
provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:REGION}
  memorySize: 128 # optional, in MB, default is 1024
  timeout: 29 # optional, in seconds, default is 6
  environment:
  httpApi:
    # set true to configure CORS policy by AWS
    # default setting is to allow all origins, methods and headers
    # replace all cors headers in lambda response
    # build own cors response when encount POST requests
    cors: true

functions:
  metadata:
    handler: handler.mint
    events:
      - httpApi:
          path: /mint
          method: get

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin